---
- name: Create users and teams
  hosts: localhost
  gather_facts: False

  vars_files:
  - vault.yml
  - vars.yml

  collections:
  - ansible.controller

  tasks:
  - name: Making sure the teams exist
    ansible.controller.team:
      name: "{{ customer }}_team1"
      description: "Created with IAC (01-user-team.yml)"
      state: present
      organization: "{{ customer }} ORG"
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False

  - name: Making sure the users exist
    ansible.controller.user:
      organization: "{{ customer }} ORG"
      username: "{{ customer }}_user1"
      password: "{{ user1_password }}"
      email: swains@redhat.com
      first_name: Sebastien
      last_name: Wains
      state: present
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      
  - name: Add user1 in team1
    ansible.controller.role:
      organization: "{{ customer }} ORG"
      user: "{{ customer }}_user1"
      target_team: "{{ customer }}_team1"
      role: member
      state: present
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False

  - name: Associate new user to organization
    ansible.controller.role:
      user: "{{ customer }}_user1"
      target_team: "{{ customer }}_team1"
      organization: "{{ customer }} ORG"
      organizations:
      - "{{ customer }} ORG"
      role: member
      state: present
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
