---
- name: Create my inventory
  hosts: localhost
  gather_facts: False

  vars_files:
  - vault.yml
  - vars.yml

  collections:
  - ansible.controller

  tasks:
  - name: Making sure the inventory exists
    ansible.controller.inventory:
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      name: "{{ customer }} INVENTORY"
      description: "Created with IAC (03-inventory.yml)"
      organization: "{{ customer }} ORG"
      state: present

  - name: Add a host to the new inventory
    ansible.controller.host:
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      inventory: "{{ customer }} INVENTORY"
      state: present
      name: localhost
      enabled: true
      variables:
        example: 123
        ansible_connection: local
