---
- name: Create my credential
  hosts: localhost
  gather_facts: False

  vars_files:
  - vault.yml
  - vars.yml

  collections:
  - ansible.controller

  tasks:
  - name: Making sure the credential exists. For the sake of the demo we didn't vault the password
    ansible.controller.credential:
      description: "Created with IAC (04-credential.yml)"
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      name: "{{ customer }} root password"
      organization: "{{ customer }} ORG"
      state: present
      credential_type: Machine
      inputs:
        username: root
        password: "{{ root_password }}"
