---
- name: Create a workflow with my new jobs
  hosts: localhost
  gather_facts: False

  vars_files:
  - vault.yml
  - vars.yml

  collections:
  - ansible.controller

  tasks:
  - name: Create workflow
    ansible.controller.workflow_job_template:
      name: "{{ customer }} WORKFLOW"
      description: "Created by IAC (06-workflow.yml)"
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      organization: "{{ customer }} ORG"
      state: present
      inventory: "{{ customer }} INVENTORY"
      ask_variables_on_launch: true
      extra_vars: {'job1_result': 'succeed', 'key': 'value', 'key2': {'subkey': 'subvalue'}}
      schema:
      - identifier: job1
        unified_job_template:
          organization:
            name: "{{ customer }} ORG"
          name: "{{ customer }} JOB 1"
          type: job_template
        related:
          success_nodes:
            - identifier: job2
          failure_nodes:
            - identifier: job3
          always_nodes: []
          credentials: []
      - identifier: job2
        unified_job_template:
          organization:
            name: "{{ customer }} ORG"
          name: "{{ customer }} JOB 2"
          type: job_template
      - identifier: job3
        all_parents_must_converge: false
        unified_job_template:
          organization:
            name: "{{ customer }} ORG"
          name: "{{ customer }} JOB 3"
          type: job_template
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes: []
          credentials: []