---
- name: 🚀🚀🚀 Start my workflow twice 🚀🚀🚀
  hosts: localhost
  gather_facts: False

  vars_files:
  - vault.yml
  - vars.yml

  collections:
  - ansible.controller

  tasks:
  - name: 🚀 Workflow launch where everything works 🚀
    ansible.controller.workflow_launch:
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      name: "{{ customer }} WORKFLOW"
      extra_vars: {'job1_result': 'succeed'}

  - name: 🚀 Workflow launch with remediation 🚀
    ansible.controller.workflow_launch:
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      name: "{{ customer }} WORKFLOW"
      extra_vars: {'job1_result': 'fail'}