---
- name: 🚀🚀🚀 Start an individual job 🚀🚀🚀
  hosts: localhost
  gather_facts: False

  vars_files:
  - vault.yml
  - vars.yml

  collections:
  - ansible.controller

  tasks:
  - name: 🚀 Job launch 🚀
    ansible.controller.job_launch:
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      job_template: "{{ customer }} provisioning"
      extra_vars: {'job1_result': 'succeed!'}
    register: output

  - debug:
      msg: "You can check the job logs at https://{{ aap2_host }}/#/jobs/playbook/{{ output.id }}"