---
- name: 💥💥💥 Simulate a disaster! 💥💥💥
  hosts: localhost
  gather_facts: False

  vars_files:
  - vault.yml
  - vars.yml

  collections:
  - ansible.controller

  tasks:
  - name: 🧨 Nuke the project 🧨
    ansible.controller.project:
      name: "{{ customer }} PROJECT"
      state: absent
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False

  - name: 🧨 Nuke the workflow 🧨
    ansible.controller.workflow_job_template:
      name: "{{ customer }} WORKFLOW"
      description: "Created by IAC"
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      state: absent

  - name: 🧨 Nuke the jobs 🧨
    ansible.controller.job_template:
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
      name: "{{ customer }} JOB {{ item }}"
      state: absent
    loop:
    - "1"
    - "2"
    - "3"

  - name: 🧨 Nuke the organization 🧨
    ansible.controller.organization:
      name: "{{ customer }} ORG"
      state: absent
      controller_host: "{{ aap2_host }}"
      controller_username: "{{ aap2_username }}"
      controller_password: "{{ aap2_password }}"
      validate_certs: False
